const actionTypes = Object.freeze({

    CUSTOMER_LOGIN_OR_REGISTER: 'CUSTOMER_LOGIN_OR_REGISTER',

    CUSTOMER_LOGOUT: 'CUSTOMER_LOGOUT',

    ADD_TO_CART: 'ADD_TO_CART',

    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',

    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',

    REMOVE_ITEM: 'REMOVE_ITEM',

    CLEAR_CART: 'CLEAR_CART',

    CLEAR_ERROR: 'CLEAR_ERROR'
});

export default actionTypes;